name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Samk1710
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate GitHub contribution snake"
          add: "output/*.svg"
